### ISSUE TITLE
Ready for grading, week 2, lab 1. It's under week 2.2

### ISSUE THREAD

**Issue by aarandarodriguez-matc** [madisoncollege-it-programs/python-scripting-aarandarodriguez-matc#1]
For step 7, I did get through all the creation of the logs but because I got a bit confused, I am not sure if I took the logs at the correct moments. I was able to push all of  them to GitHub, though. Also, in creating a directory, I had to look for "mkdir" to create the week 2 folder. I don't remember this command being talked about in the video so I wasn't sure. My first attempt failed because I used the "code" command on VS Code, as I had done for the creation of the README.md file. Sadly, I didn't know how to delete that first failed attempt called "week.save". I tried "git rm week.save" and its iterations but I didn't get it to work. I hope this doesn't take points away from my score.

Thank you,

Anas

**Comment by cethenmc** [comment]
Accepted.  The key here is that I saw you revert to a previous commit more than anything else.  Nice work!  ~Chris
