### ISSUE TITLE
Week 9 help

### ISSUE THREAD

**Issue by aarandarodriguez-matc** [madisoncollege-it-programs/python-scripting-aarandarodriguez-matc#11]
As I said, I am not sure why there's a squiggly yellow line when I import my functions script. Can you help so I can fix it?

**Comment by cethenmc** [comment]
Well done.  8 of 8.  I don't see any yellow squiggly lines, but when it comes to text colors and editing markers, they are sometimes impacted by extensions.  Do you have VS Code extensions requiring updates?  Did you install new extensions in VS Code?

I will also add that you _could_ run the tempconversion.py through its own "main()" function.  The heading of the week 9 lab very poorly indicates it in parentheses  "Script 2 - Temp Conversion (**Main**)."  You may consider modifying your tempconversion.py script or creating another (tempconversion2.py) where it will use \_\_name\_\_ to ensure the main() function runs.  Your main() function would simply include the code in your current script.
