### ISSUE TITLE
Week 10 ready to be graded

### ISSUE THREAD

**Issue by aarandarodriguez-matc** [madisoncollege-it-programs/python-scripting-aarandarodriguez-matc#12]
I am left feeling a little uneasy because I am not sure if I produced the desire output. To test it, I included an extra print for the full length of myProcList, and then minus the header.

**Comment by cethenmc** [comment]
Well done.  8 of 8.

I will also add that you _could_ run the tempconversion.py through its own "main()" function.  The heading of the week 9 lab very poorly indicates it in parentheses  "Script 2 - Temp Conversion (**Main**)."  You may consider modifying your tempconversion.py script or creating another (tempconversion2.py) where it will use \_\_name\_\_ to ensure the main() function runs.  Your main() function would simply include the code in your script.
