### ISSUE TITLE
Week 11 ready to be graded!

### ISSUE THREAD

**Issue by aarandarodriguez-matc** [madisoncollege-it-programs/python-scripting-aarandarodriguez-matc#13]
The only thing I could not match was the "optional arguments:" heading. Otherwise I think I did what I was supposed to do.

thank you,

**Comment by cethenmc** [comment]
Great work, Anas.  I think you added defaults in everything, which was not required.  In a roundabout way, when you default a value, you require it to be populated (if not by the user, then by the default value).  The only one that was required was -i (an integer), and from a user standpoint that was still the case.  **Therefore, all good!  8 of 8.**    

![image](https://user-images.githubusercontent.com/112707666/201415246-a87dbece-e98c-4a8c-9cd0-c5f6290b75ca.png)

**Comment by aarandarodriguez-matc** [comment]
Thank you. I have to admit that, compared to the other labs we have done, I found this one to be more abstract. I will have to review it prior to the final because I don't fully understand its purpose yet.
________________________________

**Comment by cethenmc** [comment]
I appreciate this feedback, Anas.  I hope to get through the grading Wed and Friday of this week.

Chris

[signature_146958654]
Chris Ethen | Information Technology Instructor
Madison College | 1701 Wright Street | Madison, WI  53704
P: 1.608.616.1099 | ***@***.******@***.***>
