### ISSUE TITLE
Week 13 ready for grading

### ISSUE THREAD

**Issue by aarandarodriguez-matc** [madisoncollege-it-programs/python-scripting-aarandarodriguez-matc#15]
Hello,

Sorry about turning in last week's lab late. I needed a break for my sanity! I should be able to catch up this week though.

thank you,

**Comment by cethenmc** [comment]
Very nice work on these two scripts.  8 out of 8.

The directions were unclear for inspect-web.py when it asked to get every link, it also wanted the href (not just the label).  With the rules being unclear, I accept the link name you provide.  I would also take just the links.  In an ideal world, I would see both.  If you would like to add to your own copy please add this under your last print statement (you are not required to reply to this issue):

print(f"{link.text}:  {link.get('href')}")
