### ISSUE TITLE
Final exam is ready to be graded.

### ISSUE THREAD

**Issue by aarandarodriguez-matc** [madisoncollege-it-programs/python-scripting-aarandarodriguez-matc#17]
I have completed the final exam script. Hopefully I included everything we needed to include in the script to get a good grade. Also, I did have to look at additional videos on YouTube for help with the socket function, so the structure looks a little different from that of the the lesson video. Thank you for everything! I enjoyed this class tremendously. --Anas

**Comment by cethenmc** [comment]
96 out of 100!

![image](https://user-images.githubusercontent.com/112707666/207212316-f2061e74-eee2-46b3-a663-51d818ec76f0.png)

**Comment by aarandarodriguez-matc** [comment]
Oh my goodness! That makes me very happy. Thank you so much. Thanks for all the support and guidance. I hope you have a great break and holidays.

Anas
________________________________

**Comment by cethenmc** [comment]
You, as well, Anas.  I hope I have the privilege of having you in another class someday!  Keep up the appetite for learning!

Chris

[signature_146958654]
Chris Ethen | Information Technology Instructor
Madison College | 1701 Wright Street | Madison, WI  53704
P: 1.608.616.1099 | ***@***.******@***.***>
