### ISSUE TITLE
My First Python Script for week 2 is ready for grading.

### ISSUE THREAD

**Issue by aarandarodriguez-matc** [madisoncollege-it-programs/python-scripting-aarandarodriguez-matc#2]
I was able to test my script on VS Code but I am not sure if it also has to run on GitHub once I push it to my repository?

thanks,

Anas

**Comment by cethenmc** [comment]
Hi, Anas.  I would like you to update your script so you can run it from the command line.

Your first line should always be the following for your scripts.  In this way, if you are running from the command line it will know what interpreter to use.  Will you please add this line to the top of your first-script.py code?

#!/usr/bin/env python3

Recall from the videos, you may also need to issue a chmod command to modify the rights to make it executable.

chmod u+x first-script.py

After this, you can execute from the command line.

./first-script.py

Please be so kind as to resubmit it, so...
1. modify the file in NetLab with the added line at the top.
2. update the file to be executable.
3. add the file to staging (git add .)
4. commit the file to your local repo. (git commit -m "changes requested to run from command line")
5. push to the git hub repository (git push)
6. reply to this same issue, saying you have completed these steps

Thanks.

~Chris

**Comment by aarandarodriguez-matc** [comment]
Good morning,

OK 😪😪

I'll work on that today. I'm glad you emailed me today because I hadn't added the line you mentioned to my current W3 lab.

thank you for the feedback,

Anas,
________________________________

**Comment by aarandarodriguez-matc** [comment]
Hello,
I believe I have completed the changes as requested.

thank you,

**Comment by cethenmc** [comment]
Thanks for turning this around so quickly, Anas!  100% on both week 2 activities.  ~Chris

**Comment by aarandarodriguez-matc** [comment]
Thank you! I am submitting this week's lab in a bit as well. I am learning a lot!
________________________________
