### ISSUE TITLE
Week 5 ready to be graded

### ISSUE THREAD

**Issue by aarandarodriguez-matc** [madisoncollege-it-programs/python-scripting-aarandarodriguez-matc#5]
I decided to create text files for my answers since they were pretty long, and rad them through my script.  I hope this doesn't mess up my script when you are testing it. I can type in the whole text in my print statements, if you want me to.

thank you,

**Comment by aarandarodriguez-matc** [comment]
Thank you,

I'd like a chance to go back in and figure it out! I will fix it.

--Anas
________________________________

**Comment by cethenmc** [comment]
Thanks, Anas.  I figured you'd like that opportunity!  Keep up the good work!

Chris

[signature_146958654]
Chris Ethen| Information Technology Instructor
Madison College | 1701 Wright Street | Madison, WI  53704
P: 1.608.616.1099 | ***@***.******@***.***>

**Comment by aarandarodriguez-matc** [comment]
I am a bit confused. When I run my script, for question 1A, my result of the len() function is 2891, which is the same number I used in my answer for Q1B. Where do you see the result of 2744?
________________________________

**Comment by cethenmc** [comment]
Hi, Anas.  Remember that when I execute your same script, it runs against my /etc/passwd file, not yours.  Mine is likely shorter than yours.  Therefore, instead of hardcoding that number into your description, you are better served dynamically printing that number in a formatted string or getting rid of the number in your description.

Does that help?  If not, please let me know.  Happy to help.

Chris

[signature_146958654]
Chris Ethen| Information Technology Instructor
Madison College | 1701 Wright Street | Madison, WI  53704
P: 1.608.616.1099 | ***@***.******@***.***>

**Comment by aarandarodriguez-matc** [comment]
Ohhhhhhh, yes, it makes total sense! It's an easy fix. I definitely did not account for that. Now I can fix it. Thank you!
________________________________

**Comment by cethenmc** [comment]
My pleasure.  I am sorry I didn't explain it better the first time.

Chris

[signature_146958654]
Chris Ethen| Information Technology Instructor
Madison College | 1701 Wright Street | Madison, WI  53704
P: 1.608.616.1099 | ***@***.******@***.***>

**Comment by aarandarodriguez-matc** [comment]
Good morning professor,

I had an additional question. When running my program again, the text files I created don't seem to be able to be read by my script and I get a message saying they do not exist. How can I fix that?
________________________________

**Comment by cethenmc** [comment]
Do you have a quick moment that we can jump on a Teams meeting and we can screen share?

Are you running the script from the same directory as your files still?  What if you placed the full directory (absolute path) with the file name?  Does it work then?

Chris

[signature_146958654]
Chris Ethen| Information Technology Instructor
Madison College | 1701 Wright Street | Madison, WI  53704
P: 1.608.616.1099 | ***@***.******@***.***>

**Comment by cethenmc** [comment]
I am on a call currently, but I should be able to jump on a screen share at about 10:35 AM if that would work for you.

Chris

[signature_146958654]
Chris Ethen| Information Technology Instructor
Madison College | 1701 Wright Street | Madison, WI  53704
P: 1.608.616.1099 | ***@***.******@***.***>


From: Ethen, Christopher M
Sent: Wednesday, October 5, 2022 9:44 AM
To: madisoncollege-it-programs/python-scripting-aarandarodriguez-matc ***@***.***>; madisoncollege-it-programs/python-scripting-aarandarodriguez-matc ***@***.***>
Cc: Comment ***@***.***>
Subject: RE: [madisoncollege-it-programs/python-scripting-aarandarodriguez-matc] Week 5 ready to be graded (Issue #5)

Do you have a quick moment that we can jump on a Teams meeting and we can screen share?

Are you running the script from the same directory as your files still?  What if you placed the full directory (absolute path) with the file name?  Does it work then?

Chris

[signature_146958654]
Chris Ethen| Information Technology Instructor
Madison College | 1701 Wright Street | Madison, WI  53704
P: 1.608.616.1099 | ***@***.******@***.***>

**Comment by aarandarodriguez-matc** [comment]
Hello,

I am at work currently but would've loved to have been on a call to figure it out. I did, however, noticed I was running the program from the Desktop directory rather than from week5, which fixed the problem. I have fixed the hardcoding to accommodate the different sizes of the /etc/passwd file.

thanks,
Anas
________________________________

**Comment by cethenmc** [comment]
Fantastic.  Thanks for letting me know.

Chris

[signature_146958654]
Chris Ethen| Information Technology Instructor
Madison College | 1701 Wright Street | Madison, WI  53704
P: 1.608.616.1099 | ***@***.******@***.***>

**Comment by cethenmc** [comment]
This looks great!  Adjusting the score to 8 of 8.
