### ISSUE TITLE
Week 6 ready to be graded.

### ISSUE THREAD

**Issue by aarandarodriguez-matc** [madisoncollege-it-programs/python-scripting-aarandarodriguez-matc#6]
I struggled with the first lab because I thought it was more complicated than it was. I thought we had to use if statements and print out the expression on the lab. Thanks for the help. For Lab B, I tried to format the text but failed. I don't like how it prints but I have a lot more homework to complete so I just let it be.

**Comment by cethenmc** [comment]
Booleans is 100%.  

FlowControl needs rework.  You were supposed to add a third door, and the text still reads...

**_You enter a dark room with two doors.
Do you g0 through door #1 or door #2?
-> 3
Invalid option. Plese enter a valid option.
->_**

You did some of the work and adding a third option on others, but the directions asked for a third door.  I will record a 5 of 8  for now, but feel free to resubmit and reply to this Issue ticket.

**Comment by aarandarodriguez-matc** [comment]
Hi there,

I did add a 3rd door, but it is door 0, a secret door that I hinted at in the description. I am a fan of RPG video games so I thought including a secret door 0 was on theme. I can change it to door number 3 instead of door 0, if it's absolutely necessary.
________________________________

**Comment by cethenmc** [comment]
Ahhhhh...my first step in checking the program is walking through it.  Then I look at the code secondarily.  It allows me less touch points when grading so many of these.  I will go back and look at it again.  Hopefully, today yet.

Thanks.

Chris

[signature_146958654]
Chris Ethen| Information Technology Instructor
Madison College | 1701 Wright Street | Madison, WI  53704
P: 1.608.616.1099 | ***@***.******@***.***>

**Comment by aarandarodriguez-matc** [comment]
I am sorry, but I will resist my urge to be creative next time. I know grading is a lot of work!
________________________________

**Comment by cethenmc** [comment]
No, no.  Please fill free to be creative, especially on this exercise!  However, what may help me in an oddity like this one is to tip me off on the issue you create.

Perhaps where you wrote this note (“For Lab B, I tried to format the text but failed. I don't like how it prints but I have a lot more homework to complete so I just let it be.”), you could have added a note that you used a secret third door😊

Thanks again!

Chris

[signature_146958654]
Chris Ethen| Information Technology Instructor
Madison College | 1701 Wright Street | Madison, WI  53704
P: 1.608.616.1099 | ***@***.******@***.***>

**Comment by cethenmc** [comment]
Hi, Anas.  Fun work!  So I cannot say I know anything about RPG video games.  When I sneak in the secret door, is this the intended behavior?  After going through the secret door by choosing 0, I chose 0 again when it gave me options 1, 2, and 3.  When it told me I died, it gave me another input ### entry (see the bold italicized).  It is fun and mostly there.  I will raise to a 7 of 8 until I see your answer to this peculiarity.

**$ ./flowcontrol.py** 
You enter a dark room with two doors.
Do you g0 through door #1 or door #2?
-> **0**
Mhhhhhh. You have chosen quite a pecular path.
Are you certain you want to go through with it?


1. Let me think about it.
2. I've never been more sure.
3. Curiosity killed the cat, So I better not.

-> **0**
You have died.
**_->**0**_**           

Un undead cat comes out of nowhere and pounces on you. The cat eats your face off.

**Comment by aarandarodriguez-matc** [comment]
Alright, I think I fixed the problem. I switched the if statement for a while loop to make sure the user picked one of the valid options.

**Comment by cethenmc** [comment]
Awesome!  Great work and you satisfied the requirement for your door addition.  8 of 8 recorded.  I did notice that you did not put the loop at every location...but you still satisfied all requirements.
![image](https://user-images.githubusercontent.com/112707666/200029801-b6e27a15-b502-4047-8225-a25197598338.png)
