### ISSUE TITLE
midterm-if.py is ready to be graded.

### ISSUE THREAD

**Issue by aarandarodriguez-matc** [madisoncollege-it-programs/python-scripting-aarandarodriguez-matc#8]
I left out the "else" statement at the end of the script because I wasn't 100% if it was necessary or even to define it. Either way, I got the right output so I think I did it right. Thank you.

**Comment by cethenmc** [comment]
Midterm-if:  All concepts you used were concepts learned in class, which was nice to see.  I assume you could not recall a method to extract the line number as requested.  As a result of not extracting the line number (what if we placed gaps in the line number column) and converting it to an int (which was a hint to help you know what you might use to extract), you will receive a score of 29/33.  You will need to explain why you had a couple of "lin_num = lin_num" lines in your script sometime.
